server:
 port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/myproject
    username: myproject
    password: 123
  jpa:
    properties:
        hibernate: hibernate:dialect:org:hibernate:dialect:PostgreSQLDialect;
    hibernate:
       ddl-auto: create-drop
   